### ISSUE TITLE
El Capitan sanity check + ARC conversion

### ISSUE THREAD

**Issue by johndpope** [krevis/MIDIApps#45]
Hi Kurt,

I upgraded a couple of my systems to El Capitan GM the other day - and have some major beach ball regression in my http://komposer.io app. It was all working so sweet in Yosemite. 
I was thinking of chipping in to help with some ARC conversion. 
What are your thoughts? Did you try El Capitan?  I'll send you an invite to my app. 

JP

**Comment by krevis** [comment]
I haven't tried El Capitan yet; I will give it a shot this weekend.  I don't know of any changes that would cause issues in SnoizeMIDI, but anything's possible.  

If you are getting beachballs in your app, have you sampled the app (using Activity Monitor or Instruments) to see what's happening when it locks up?  Does the same thing happen in other MIDI apps, for instance Audio MIDI Setup?

If you have changes to convert to ARC I would love to integrate them!  But I wouldn't expect that to fix (or cause) any performance issues.

**Comment by krevis** [comment]
I'm not seeing any obvious problems with MIDI Monitor or SysEx Librarian running on El Capitan.  

I didn't see any beachballs in Komposer, but I only just launched the app and saw a bunch of mostly blank windows.  I don't know how to test your app.

Without any more information, the best I can suggest is that you check for old and outdated drivers in /Library/Audio/MIDI Drivers. If you have a bad driver it's very likely that apps using MIDI will lock up. Any MIDI app would do that, Audio MIDI Setup is easiest to test since everybody has it.

I'm closing this since I don't see anything actionable for me to do.

**Comment by johndpope** [comment]
fyi
![screen shot 2015-09-22 at 7 23 49 am](https://cloud.githubusercontent.com/assets/289994/10005604/823cc40c-60fb-11e5-849c-942fb59d7290.png)

**Comment by johndpope** [comment]
I wouldn't be too concerned with that bug above - more of a motivation to ARC everything. 
It was occurring under edge case that non midi instruments were turned on.

It's weird - I'm seeing problems with AudioToolbox core functionality. 
I hope the el captian GM fixes this. Otherwise I'll have to create a radar.
![screen shot 2015-09-22 at 7 31 33 am](https://cloud.githubusercontent.com/assets/289994/10005683/0187da44-60fc-11e5-897f-49da96a1f8c7.png)

**Comment by krevis** [comment]
If you have an NSData object that crashes when retaining it, you have big problems. Where did that NSData come from? Did you set a breakpoint on malloc_error_break (as the message suggests) and see what happens? Did you try the [other memory debugging tools](https://developer.apple.com/library/mac/recipes/xcode_help-scheme_editor/Articles/SchemeDiagnostics.html)?

If you switched to ARC, you wouldn't have to write the call to -retain, but the compiler would still be doing exactly the same thing. So it's unlikely that switching to ARC would fix this bug.

I don't have much experience with AudioToolbox so I can't supply much help there, sorry.
