### ISSUE TITLE
incorrect midi note labeling according to ableton

### ISSUE THREAD

**Issue by iphizzle** [krevis/MIDIApps#91]
hello. love the app. always use it for my 2 midi devices. 

anyway, i was trying to assign a sound to a rim of my 3rd tom in ableton. i didn’t know what note to assign it to, so i used midi monitor to see what note the rim was sending. it kept saying, “A#3.” and when i found the A#3 spot to put the sound, in ableton, i put it there. but i wasn’t getting any sound. i couldn’t figure it out. then, i turned on an option that tracks each note received, in ableton, and it brings focus to a spot where you can drop a sound to that note. and apparently, the right note is, “A#2.”

just thought i’d share. midi monitor always shows the notes coming though. didn’t know they could be wrong until now tho. thank you.

**Comment by krevis** [comment]
This is not a MIDI Monitor bug.  There is an unfortunate and longstanding lack of standardization on how to number the octaves of MIDI notes. Middle C is defined to be note 60 (decimal), but there is no standard for whether that is displayed as C3, C4, or something else. This has caused confusion for decades.

It's impossible for MIDI Monitor to always display the same octave as your device or software, since it doesn't know what your devices or software are.  That's why MIDI Monitor has this preference to control the display:

<img width="462" alt="Screen Shot 2021-07-23 at 9 27 55 AM" src="https://user-images.githubusercontent.com/237747/126813436-21492973-ec2c-490a-a68c-ab4f02bc7f76.png">

What do you have this set to?  And where exactly in Ableton Live are you displaying the note A#2 -- do you have a screenshot?  (Are you sure it's Live and not a 3rd party plugin?)

More references:
[Octaves (OnMusic Dictionary)](https://dictionary.onmusic.org/appendix/topics/octaves)
[Helmholtz Pitch Numbering](http://www.theoreticallycorrect.com/Helmholtz-Pitch-Numbering/)
[MIDI Octave and Note Numbering Standard, or lack thereof](https://www.midi.org/forum/830-midi-octave-and-note-numbering-standard)
or just google for "midi c3 c4" or something similar.
