### ISSUE TITLE
Use the common "CMD + K" shortcut to clear the log.

### ISSUE THREAD

**Issue by besi** [krevis/MIDIApps#92]
I use the Terminal.app a lot and when I do something new I often use `CMD + K` in order to clear the window.
It would be fantastic if I could use that shortcut to clear the log of the MidiMonitor.

Anyhow, thanks for making such a useful utility!

**Comment by krevis** [comment]
Glad you're finding it useful.

This should already work in the current version of MIDI Monitor, 1.4.1.  There is a menu command `Events > Clear Events` which has a shortcut `Command-K`.  That's been present since at least version 1.3 , released in 2012... so this has already been done for at least 10 years now.

If command-K doesn't work for you, does selecting that menu command work?  Do you have the current focus anywhere in particular (e.g. do you have a message selected, or one of the sources, or something else)?  

Do you perhaps have a custom shortcut set up to handle Command-K?  Look in System Preferences, Keyboard, Shortcuts.

**Comment by besi** [comment]
I'll check again. But if you say it's there then maybe I did oversee it.
